//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.LlmSwarmNav
{
    [Serializable]
    public class Vector3StampedArrayMsg : Message
    {
        public const string k_RosMessageName = "llm_swarm_nav/Vector3StampedArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public Geometry.Vector3Msg[] vector;

        public Vector3StampedArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.vector = new Geometry.Vector3Msg[0];
        }

        public Vector3StampedArrayMsg(Std.HeaderMsg header, Geometry.Vector3Msg[] vector)
        {
            this.header = header;
            this.vector = vector;
        }

        public static Vector3StampedArrayMsg Deserialize(MessageDeserializer deserializer) => new Vector3StampedArrayMsg(deserializer);

        private Vector3StampedArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.vector, Geometry.Vector3Msg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.vector);
            serializer.Write(this.vector);
        }

        public override string ToString()
        {
            return "Vector3StampedArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\nvector: " + System.String.Join(", ", vector.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
